{% set version = "0.3.3" %}

package:
  name: pvlib-python
  version: {{ version }}

source:
  fn: pvlib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pvlib/pvlib-{{ version }}.tar.gz
  md5: 1fdef1d50270d22f8d89d9032fca2730

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.2
    - pandas >=0.13.1
    - pytz
    - six

  run:
    - python
    - numpy >=1.8.2
    - pandas >=0.13.1
    - pytz
    - six

test:
  imports:
    - pvlib

about:
  home: https://github.com/pvlib/pvlib-python
  license: BSD 3-Clause
  summary: 'The PVLIB toolbox provides a set functions for simulating the performance of photovoltaic energy systems.'

extra:
  recipe-maintainers:
    - wholmgren
