travis:
  secure:
    BINSTAR_TOKEN: ipX8AET9KMR+xjlXyG8og5mjtDQaZOZs48Wj/iYYbTrl1ai8FA4TAri12wHEUZlKu0+HFGmAs61ZRmaIthMMI7qLUiA1TOtXi95MNaxWCaQSFRTpZpBU25U3dZSw6RONK8zJo8iFk20XZqMHy9RbSjO/CE7qpIqohSYoOg/NVVU5TqprfjmtcZqU6JMe7LazkB0WZMinvijTZOnEIB/nL/KaQQTCn8+ajUMR55aPj/3hoMjhp0Dc2UzT86xGwM3wVtWLAzZ5YfxVV1lSZYKI1RgD0el/feSJXPPfwVYWTYb1aOQ+cKqPGuBKKWA6qaV+zOlJRkc9zOSTq+Jgfk/ABH01oAan6a4L0G/CWAx1f7rlMrEDeD9HxQ73dXLXkX/07omHDBBB4kqnmHQpx0M4OaPwFYPdOSmInbTeP+qfF1nhNOwq5HIB8keNOhN2gf3aHShSjkHv/N85HwERZEirbQ1DpLrGif9+uIwrYNgfh0WMvAuXslKtyVHZ5Z/mk0bQHFcuau3YmLEHYItZvIEKh8PV6g3sbYBLfRqCb27SctTivzeWKjmYEV6KQe3M0CcTy5T2ScEDAa9gFynTBDwdHAmPsqBfzzPtv8YUsQfTLwL1ErnERRazokM1qzJDTHBkUw7nwvF9E8VrnglznNbsQX54u2XZ9En4oajaukryZBs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
