travis:
  secure:
    BINSTAR_TOKEN: t7l9AUP5FILuRFXCa033UoYsy+Mxx3Qt3t2CQeqqeaq7cXlY6aLjG6HwbdmEy7SD227g0WHh0aKEF1C/pZZ+vXHS3L/c6vUlp8W1pTL2DS0vnDamuEFuQ0yqnvZjidcSwUWNfDutKzhqh/27OIG9FkdeMkbFP6gb+QbTn7aTZQg17udGBKF1ochFtCK7E9CmStAwQIcSYLIWxT1fcuwkro+ebP+8dq7DodunCfEgGKv/tLGM6qXn/fd7yNrmqsAno3tna6PyHnCZUjx3bYPM7V7THL1Vdc01gaVF8uMXhEXBXng/oYQO8bCo2J0y8B6JtNJIWbhIo+iHpYPgt5v8/Af2u9YtliI2yVu+VdfJ9Dz5fS+0pV86yMI1tU8eMrY0/PRNUJP0fz58/6dN34v9pOnkcHAQ/eKrSyimymu5lSs4YyvsJ5whNbCNjKRQxk5uJ5VHpgfvE9IyPfOM9c39g3pZQtYEui1jygGiK33WkOh3cFreB7wuU6oFiEGIMgCM/RuAPEd4Nq0TlAbN4fcF6JUb3bUWwrS54rZV6mefDbP6X5zbBQyIsgP40AaUG1hx5B1CWNw5P2H4w8s1w6m5z/9DQ1B0A6zgXJaX22+zgCF0wbfEJaGwuvY62V8xFcqbEp6vAuchF8RTcjthz8JaZAY29XeoTO3o77DJ12/KmrI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
